model:
    name: two_view_pipeline
    extractor:
        name: extractors.akaze_opencv
        max_num_keypoints: 2048
    matcher:
        name: matchers.nn_opencv
        feature: akaze
        ratio_test: False
        mutual_check: True
benchmarks:
    tum:
        data:
            pairs: tum_facade/pairs_uav.txt
            preprocessing:
                side: long
                resize: 1600
                create_mask: True
        eval:
            estimator: opencv
            ransac_th: 10.0