model:
    name: two_view_pipeline
    extractor:
      name: extractors.disk_kornia
      max_num_keypoints: 2048
      detection_threshold: 0.0
    matcher:
      name: matchers.lightglue_pretrained
      features: disk
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    tum:
        data:
            pairs: tum_facade/pairs_uav.txt
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: opencv
            ransac_th: 10.0