model:
    name: two_view_pipeline
    matcher:
        name: matchers.kornia_loftr
        topk: 2048
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1024
        eval:
            estimator: opencv
            ransac_th: -1
    hpatches:
        eval:
            estimator: opencv
            ransac_th: -1
        model:
            matcher:
                topk: 1024
    tum:
        data:
            preprocessing:
                side: long
                resize: 1024
        eval:
            estimator: opencv
            ransac_th: 10.0