model:
    name: two_view_pipeline
    extractor:
        name: extractors.sift
        detector: opencv
        max_num_keypoints: 2048
        detection_threshold: 0.00666666
        nms_radius: -1
        rootsift: True
    matcher:
        name: matchers.flann_opencv
        feature: sift
benchmarks:
    tum:
        data:
            pairs: tum_facade/pairs_uav.txt
            preprocessing:
                side: long
                resize: 1600
                create_mask: True
        eval:
            estimator: opencv
            ransac_th: 10.0